"""create_followings_followers_table

Revision ID: 5affe6fba931
Revises: e1f45fc13159
Create Date: 2023-01-29 15:38:18.966069

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '5affe6fba931'
down_revision = 'e1f45fc13159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followings_followers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('followedUserId', sa.Integer(), nullable=False),
    sa.Column('followerUserId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followedUserId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['followerUserId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE followings_followers SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followings_followers')
    # ### end Alembic commands ###
