"""empty message

Revision ID: cc7ae7517ea3
Revises: 665566b69243
Create Date: 2023-02-01 23:39:39.508983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc7ae7517ea3'
down_revision = '665566b69243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image', sa.String(length=20), nullable=True))
    op.drop_column('users', 'image_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_file', sa.VARCHAR(length=20), nullable=True))
    op.drop_column('users', 'image')
    # ### end Alembic commands ###
